# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
   ['main.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\calculate\calculate.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\Animation\indexAnimation.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\Animation\utils.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\Widget\buttonFrame.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\Widget\matrixTable.py',
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\calculateWidget.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\chooseWidget.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\indexAside.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\matrixWidget.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\topBar.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\welcomeWidget.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\Utils\utilsCalculate.py', 
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\Utils\utilsErrorHandle.py'],
    pathex=[r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject',
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\calculate',
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI',
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\Animation',
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\UI\Widget',
    r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\Utils'],
    binaries=[(r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\main.ico', '.')],
    datas=[(r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\success.png', './res/icon'), 
    (r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\back.png', './res/icon'), 
    (r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\cancel.png', './res/icon'), 
    (r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\caution.png', './res/icon'), 
    (r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\continue.png', './res/icon'), 
    (r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\error.png', './res/icon'), 
    (r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\help.png', './res/icon'), 
    (r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\main.ico', './res/icon'), 
    (r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\OK.png', './res/icon')],
    hiddenimports=['calculate', 
    'indexAnimation', 
    'utils', 
    'buttonFrame', 
    'matrixTable',
    'calculateWidget', 
    'chooseWidget', 
    'indexAside', 
    'matrixWidget', 
    'topBar', 
    'welcomeWidget', 
    'utilsCalculate', 
    'utilsErrorHandle'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ORC',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r'C:\Users\Dawn\Desktop\TEST\ORProject\ORProject\res\icon\main.ico'
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ORC',
)
